POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Movimentação dos equipamentos DGi",
  "details": "Evento para mudança de lugar dos equipamentos da DGI",
  "maximumAtendees": 100
}

###

POST http://localhost:3333/events/53713fc2-06bd-47b6-895d-454edbd654fc/atendees
Content-Type: application/json

{
  "name": "Rafael Petersen",
  "email": "rafael@email.com"
}

###
GET http://localhost:3333/events/99128243-88bf-4a87-84c8-ff1eb6eee8a0

###
GET http://localhost:3333/atendees/10/badge


###
GET http://localhost:3333/atendees/5/check-in

###
GET http://localhost:3333/events/53713fc2-06bd-47b6-895d-454edbd654fc/atendees